# This file is used by cpanel git to automatically deploy when pushing to the distant repo
---
deployment:
  tasks:
    - export GIT_WORK_TREE=/home/jallet/sites/test.jallet.org/web/ext/themes/simple
    - /usr/local/cpanel/3rdparty/lib/path-bin/git checkout -f

